# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [48]:
import numpy as np

In [49]:
arr = np.arange(1, 11)  # 1~10
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[0], arr[4], arr[-1], arr[-10]

(1, 5, 10, 1)

In [51]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
arr2[0][1], arr2[1][2], arr2[2][3]

(2, 7, 12)

In [53]:
arr2[0, 1], arr2[1, 2], arr2[2, 3]  # numpy에서는 다차원 indexing

(2, 7, 12)

In [54]:
arr2[-1][-2]

11

## 5-2. 슬라이싱

### 1차원 배열

In [55]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# 3~끝까지 슬라이싱 ([start:end:step])
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[2:5]

array([3, 4, 5])

In [58]:
# 처음~5까지 슬라이싱
arr[:5]

array([1, 2, 3, 4, 5])

In [59]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# 슬라이싱을 한 후에 값을 변경하면 원본에 영향을 미칠까?
new_arr = arr[:5]
new_arr

array([1, 2, 3, 4, 5])

In [62]:
new_arr[0] = 100
new_arr

array([100,   2,   3,   4,   5])

In [63]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [64]:
copy_arr = np.copy(arr)
copy_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [65]:
arr[0] = 1
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2차원 배열

In [66]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
# 첫번째 행을 모두 가져오기
arr2[0], arr2[0, :]

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [68]:
# 세번째 열을 모두 가져오기
arr2[:, 2]

array([ 3,  7, 11])

In [69]:
# 첫번째, 두번째 행을 모두 가져오기
arr2[:2, :], arr2[:2]

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [70]:
# 두번째, 세번째 열을 모두 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [71]:
# [[2, 3]
#  [6, 7]] 가져오기
arr2[:2, 1:3]    

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [72]:
# 1차원 배열
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
# 1, 3, 5로 된 배열을 만들기
np.array([arr[0], arr[2], arr[4]])

array([1, 3, 5])

In [74]:
# 슬라이싱 [start:end:step]
arr[:5:2]

array([1, 3, 5])

In [75]:
# Fancy 인덱싱 
arr[[0, 2, 4]]

array([1, 3, 5])

In [76]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
# [[1, 2, 3, 4]
#  [9, 10, 11, 12]]
np.array([arr2[0], arr2[2]])

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [78]:
# Fancy 인덱싱
arr2[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [79]:
# 주의
arr2[0, 2] # arr2[0][2]

3

In [80]:
# 슬라이싱
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [81]:
# Fancy 인덱싱
arr2[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [82]:
## 5-4. Boolean 인덱싱
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [83]:
# cond = [False, True, False, False, True]
arr[[False, True, False, False, True]]

array([1, 4])

In [84]:
arr > 2

array([False, False, False,  True,  True])

In [85]:
arr[arr > 2]

array([3, 4])

In [86]:
# 짝수만 뽑기
arr % 2 == 0

array([ True, False,  True, False,  True])

In [87]:
arr[arr % 2 == 0]

array([0, 2, 4])

In [88]:
# 0, 3, 4
(arr < 1) | (arr > 2)

array([ True, False, False,  True,  True])

In [93]:
arr[(arr < 1) | (arr > 2)]

array([0, 3, 4])

In [90]:
# 2, 3
(arr > 1) & (arr < 4)

array([False, False,  True,  True, False])

In [91]:
arr[(arr > 1) & (arr < 4)]

array([2, 3])